featureZett/signInScreen
teamslogup/react-native-growup pull request #3
Opened 2022-06-10 10:11 UTC by slogup-zett

## 작업사항
- feat: SignInScreen

## 주의사항
- 내용을 적어주세요.

2022-06-10 14:00 UTC, jessehj requested changes
몇가지 사내 규칙이랑 다른 부분을 제외하면 큰 문제는 없어보입니다 
수고하셨어요👍

-Screen 은 일반적으로 대부분의 데이터나 상태관리를 하기때문에 쉽게 코드가 길어지는 곳입니다.
가독성 유지를 위해 순수함수들은 별도 파일로 분리하고, 컴포넌트들도 어느정도는 추상화를 하는것이 좋아보입니다.

2022-06-10 14:00 UTC, jessehj commented on src/components/atoms/Button/index.tsx
> +const backgroundColorTable: ColorTable = {
컴포넌트 폴더 내 utils.ts 파일을 만들어서 코드를 분리시키는것이 가독성 측면에서 좋을것 같습니다.

2022-06-10 14:00 UTC, jessehj commented on src/components/atoms/Button/index.tsx
> +const StyledPressable = styled(Pressable)<Required<ButtonProps>>`
스타일 컴포넌트는 styles.ts 파일로 분리해주세요
컴포넌트명은 구분이 필요없다면 최대한 간결하게 만들어주세요

사용시에는 
```
import * as Styled from './styles'; 

<Styled.Pressable ... />
```
이런형식으로 통일해주세요

2022-06-10 14:00 UTC, jessehj commented on src/components/atoms/Input/index.tsx
> +      {helperText && <HelperText error={error}>{helperText}</HelperText>}
이 구문은 helperText가 빈문자열일때 에러가 납니다. 
!!helperText 로 boolean 캐스팅을 해주거나 삼항 연산자를 써주세요

2022-06-10 14:00 UTC, jessehj commented on src/screens/SignInScreen/index.tsx
> +          '잘못된 이메일 형식입니다.',
문자열 리소스들을 포함한 상수 값들은 별도 파일로 관리해주세요

2022-06-10 14:00 UTC, jessehj commented on src/screens/SignInScreen/index.tsx
> +            로그인
항상 중괄호로 묶어서 써주세요
`<Button>{'로그인'}</Button>`

2022-06-10 14:00 UTC, jessehj commented on src/screens/SignInScreen/index.tsx
> +            size="large"
컴포넌트 프롭들 중괄호로 항상 묶어주세요

2022-06-11 13:18 UTC, slogup-any commented on src/assets/images/index.ts
> +
이미지 파일 리소스명은 kebab-case 로 변경해주세요 :)

[01_NAMING#리소스-파일-폰트-이미지-로티파일-등](https://github.com/teamslogup/react-native-boilerplate/wiki/01_NAMING#%EB%A6%AC%EC%86%8C%EC%8A%A4-%ED%8C%8C%EC%9D%BC-%ED%8F%B0%ED%8A%B8-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%A1%9C%ED%8B%B0%ED%8C%8C%EC%9D%BC-%EB%93%B1)

2022-06-11 14:55 UTC, slogup-any commented on src/components/atoms/Button/index.tsx
> +  height: ${props => heightTable[props.size]};
props 는 구조분해 할당을 해주는게 깔끔할것같네요 :)

```
background-color: ${({ theme, variant, disabled, colorStyle }) =>
    backgroundColorTable[variant][disabled ? 'disabled' : colorStyle](theme)};
```

2022-06-11 15:27 UTC, slogup-any commented on src/components/atoms/CheckBox/index.tsx
> +
`disabled` props는 어떻게 사용되는건가요? :)

2022-06-11 16:30 UTC, slogup-any commented on src/components/atoms/Divider/index.tsx
> +`;
`thickness` "px" 단위가 필요할것 같습니다. warning 체크 해주세요 :)

2022-06-11 16:38 UTC, slogup-any commented on src/components/atoms/CheckBox/index.tsx
> +
View 에서 `display: flex` 가 기본값이기 때문에 따로 스타일에 추가할 필요는 없어보입니다 :)

[reactnative.dev/docs/layout-props#display](https://reactnative.dev/docs/layout-props#display)

2022-06-11 16:44 UTC, slogup-any commented on src/components/atoms/Icon/index.tsx
> +`;
`border-radius` "px" 추가 해주세요~

2022-06-13 01:09 UTC, slogup-zett commented
@jessehj @slogup-any 말씀해주신 사항들 모두 반영해서 push 했습니다!..

2022-06-13 15:19 UTC, safience-any commented
코드량이 많아서 자세히 보긴 무리인것 같으니
잘 했으리라 믿고 merge 하겠습니다 고생하셨어요. 👏

2022-06-13 15:23 UTC, merged